name: fleetiq_shared
description: Shared validations, logs, and storage mocks for FleetIQ applications.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.0
