server:
  port: 8086

spring:
  application:
    name: fleetiq-driver-service
  datasource:
    url: jdbc:postgresql://localhost:5432/fleetiq
    username: fleetiq
    password: fleetiq
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: false
    locations: classpath:db/migration
  redis:
    url: rediss://default:gQAAAAAAATsFAAIgcDI3MWI0OWVmYTg0NjA0MTVkOTc0M2NiOGRhMzg1ZmRhMQ@verified-dodo-80645.upstash.io:6379

