ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS latitude NUMERIC(10, 6);
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS longitude NUMERIC(10, 6);
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS speed_kmh NUMERIC(5, 2);
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS heading NUMERIC(5, 2);
