ALTER TABLE vehicles ALTER COLUMN latitude TYPE DOUBLE PRECISION;
ALTER TABLE vehicles ALTER COLUMN longitude TYPE DOUBLE PRECISION;
ALTER TABLE vehicles ALTER COLUMN speed_kmh TYPE DOUBLE PRECISION;
ALTER TABLE vehicles ALTER COLUMN heading TYPE DOUBLE PRECISION;
