server:
  port: 8084
  servlet:
    context-path: /

spring:
  application:
    name: fleetiq-tracking-service
  
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/fleetiq_dev}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgressecret}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
  
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  redis:
    url: rediss://default:gQAAAAAAATsFAAIgcDI3MWI0OWVmYTg0NjA0MTVkOTc0M2NiOGRhMzg1ZmRhMQ@verified-dodo-80645.upstash.io:6379
logging:
  level:
    root: INFO
    com.fleetiq.tracking: DEBUG
    org.springframework.redis:
    url: rediss://default:gQAAAAAAATsFAAIgcDI3MWI0OWVmYTg0NjA0MTVkOTc0M2NiOGRhMzg1ZmRhMQ@verified-dodo-80645.upstash.io:6379
management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

# Application-specific Custom Settings
app:
  jwt:
    secret: "9a763845-a7b6-4bfa-b9a3-5c8e3a246800-super-secret-key-that-is-long-enough-32bytes"
